#!/bin/bash

# This script generates a Markdown file from the README.ipynb Jupyter notebook.
# Normally, the hope is that the Jupyter notebook would be enough, since GitHub can render it,
# but as it turns out, it doesn't render if it's used as a README in a directory,
# but will render if _and only if_ the individual file is opened
# (see: https://github.com/github/markup/issues/929)
# Hence, we make do with what we have and we convert to markdown for readers' convenience.
#
# This script requires jupyter to be installed on your machine.

set -e

jupyter nbconvert --execute --to markdown README.ipynb
printf '%s\n\n%s' "<!-- This Markdown file was autogenerated from README.ipynb using the generate_readme.sh script. DO NOT MODIFY THIS FILE DIRECTLY. -->" "$(cat README.md)" > README.md
